export interface CurrentFileLntOptions {
    useUnitCheck: boolean;
    includeDirs: string[];
    systemIncludeDirs?: string[];
    defines: string[];
    standard: string;
    pchHeader?: string;
}

export function generateCurrentFileLnt(options: CurrentFileLntOptions): string {
    const lines: string[] = [];

    lines.push("// Generated by VS Code PC-lint Plus extension.");
    lines.push("// Do not edit.");
    lines.push("");
    lines.push("// Output format for parser");
    lines.push("-width=0");
    lines.push("-h1");
    lines.push('-"format=%f|%l|%C|%t|%n|%m"');
    lines.push("+ffn");
    lines.push("");

    if (options.useUnitCheck) {
        lines.push("// Fast current-file mode");
        lines.push("--unit_check");
        lines.push("");
    }

    if (options.pchHeader && options.pchHeader.trim().length > 0) {
        lines.push("// Optional PCH");
        lines.push(`-pch(${options.pchHeader})`);
        lines.push("");
    }

    appendIncludeDirs(lines, "// Dynamic include directories", options.includeDirs);
    appendIncludeDirs(lines, "// Dynamic system include directories", options.systemIncludeDirs ?? []);

    if (options.defines.length > 0) {
        lines.push("// Dynamic defines");
        for (const define of options.defines) {
            lines.push(`-d${define}`);
        }
        lines.push("");
    }

    if (options.standard.trim().length > 0) {
        lines.push("// Language standard");
        lines.push(`-std=${options.standard}`);
        lines.push("");
    }

    return lines.join("\n");
}

function appendIncludeDirs(lines: string[], label: string, includeDirs: string[]): void {
    if (includeDirs.length === 0) {
        return;
    }

    lines.push(label);
    for (const includeDir of includeDirs) {
        lines.push(`-i${includeDir}`);
    }
    lines.push("");
}
